# Generated by Django 4.0.4 on 2022-04-22 12:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('nickname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=7)),
                ('fixed_classes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('nickname', models.OneToOneField(db_column='nickname', on_delete=django.db.models.deletion.CASCADE, to='EducationalWeb.peoples')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=3)),
                ('grouping', models.CharField(max_length=50)),
                ('nickname', models.OneToOneField(db_column='nickname', on_delete=django.db.models.deletion.CASCADE, to='EducationalWeb.peoples')),
            ],
        ),
    ]
