# Generated by Django 4.0 on 2022-06-08 15:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('clazz', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=10)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=3)),
                ('school', models.CharField(max_length=100)),
                ('week', models.CharField(max_length=8)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('weight', models.PositiveSmallIntegerField()),
                ('value', models.PositiveSmallIntegerField()),
                ('theme', models.CharField(max_length=5000)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=7)),
                ('fixed_classes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=3)),
                ('grouping', models.CharField(max_length=50)),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EducationalWeb.mark')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('nickname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('school', models.CharField(max_length=100)),
                ('is_student', models.BooleanField(default=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EducationalWeb.student')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EducationalWeb.teacher')),
            ],
        ),
    ]
