# Generated by Django 4.0.4 on 2022-04-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
