# Generated by Django 4.0 on 2022-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='weight',
            field=models.CharField(max_length=2),
        ),
    ]
