# Generated by Django 4.0 on 2022-06-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['nickname']},
        ),
    ]
