# Generated by Django 4.1.dev20220506075046 on 2022-05-10 15:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalWeb', '0002_rename_student_students_rename_teacher_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=3)),
                ('school', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=10)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('clazz', models.CharField(max_length=3)),
                ('week', models.CharField(max_length=8)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('value', models.IntegerField()),
                ('theme', models.CharField(max_length=5000)),
                ('subject', models.CharField(max_length=100)),
                ('nickname', models.OneToOneField(db_column='nickname', on_delete=django.db.models.deletion.CASCADE, to='EducationalWeb.peoples')),
            ],
        ),
    ]
