# Generated by Django 4.1 on 2022-05-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalWeb', '0003_classes_diary_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='id',
        ),
        migrations.AddField(
            model_name='peoples',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='students',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EducationalWeb.marks'),
        ),
        migrations.AlterField(
            model_name='students',
            name='nickname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='nickname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
