# Generated by Django 4.0 on 2022-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalWeb', '0005_remove_marks_id_remove_students_marks_marks_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoples',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
